window.SolarSim = window.SolarSim || {};
window.SolarSim.settings = window.SolarSim.settings || {};

window.SolarSim.settings.schema = {
    graphics: {
        label: "Graphics",
        summary: "Renderer, display, frame pacing, and visual effects.",
        description: "Change the graphics according to preference.",
        controls: [
            {
                key: "resolution",
                label: "Resolution",
                type: "select",
                defaultValue: "1920x1080",
                owner: "renderer",
                options: [
                    { value: "1280x720", label: "1280x720", description: "Performance preset" },
                    { value: "1920x1080", label: "1920x1080", description: "Default" },
                ],
            },
            {
                key: "displayMode",
                label: "Display mode",
                type: "select",
                defaultValue: "windowed",
                owner: "renderer",
                options: [
                    { value: "windowed", label: "Windowed" },
                    { value: "borderlessFullscreen", label: "Borderless fullscreen" },
                    { value: "fullscreen", label: "Fullscreen" },
                ],
            },
            {
                key: "fpsLimit",
                label: "FPS limit",
                type: "select",
                defaultValue: "60",
                owner: "renderer",
                options: [
                    { value: "30", label: "30" },
                    { value: "60", label: "60" },
                    { value: "120", label: "120" },
                    { value: "unlimited", label: "Unlimited" },
                ],
            },
            {
                key: "renderQuality",
                label: "Render quality preset",
                type: "select",
                defaultValue: "medium",
                owner: "renderer",
                description: "Maps to sphere geometry detail, texture quality, and trail quality.",
                options: [
                    { value: "low", label: "Low" },
                    { value: "medium", label: "Medium" },
                    { value: "high", label: "High" },
                ],
                mapsTo: {
                    low: { sphereGeometryDetail: 16, textureQuality: "low", trailQuality: "low" },
                    medium: { sphereGeometryDetail: 32, textureQuality: "medium", trailQuality: "medium" },
                    high: { sphereGeometryDetail: 64, textureQuality: "high", trailQuality: "high" },
                },
            },
            {
                key: "antiAliasing",
                label: "Anti-aliasing",
                type: "boolean",
                defaultValue: true,
                owner: "renderer",
            },
            {
                key: "postProcessing",
                label: "Post-processing",
                type: "booleanGroup",
                defaultValue: {
                    bloom: false,
                    motionBlur: false,
                    depthOfField: false,
                },
                owner: "renderer",
                options: [
                    { value: "bloom", label: "Bloom" },
                    { value: "motionBlur", label: "Motion blur" },
                    { value: "depthOfField", label: "Depth of field" },
                ],
            },
        ],
    },
    simulation: {
        label: "Simulation",
        summary: "Backend-owned physics configuration.",
        description: "Control certain backend settings.",
        controls: [
            {
                key: "physicsIntegrator",
                label: "Physics integrator",
                type: "select",
                defaultValue: "velocityVerlet",
                owner: "python",
                options: [
                    { value: "velocityVerlet", label: "Velocity Verlet" },
                    { value: "euler", label: "Euler" },
                    { value: "rk4", label: "RK4" },
                ],
            },
            {
                key: "fixedTimestep",
                label: "Fixed timestep",
                type: "readonly",
                defaultValue: "Backend controlled",
                owner: "python",
                description: "Required by the simulation loop. The frontend may display this but must not mutate it.",
            },
            {
                key: "trailSystem",
                label: "Trail system",
                type: "select",
                defaultValue: "medium",
                owner: "renderer",
                description: "Controls visual trail retention only.",
                options: [
                    { value: "off", label: "Off" },
                    { value: "short", label: "Short" },
                    { value: "medium", label: "Medium" },
                    { value: "long", label: "Long" },
                    { value: "infinite", label: "Infinite" },
                ],
            },
        ],
    },
    camera: {
        label: "Camera",
        summary: "Mouse input and camera distance limits.",
        description: "Mouse speed and camera configuration.",
        controls: [
            {
                key: "mouseSensitivity",
                label: "Mouse sensitivity",
                type: "range",
                defaultValue: 1,
                owner: "camera",
                min: 0.1,
                max: 3,
                step: 0.1,
            },
            {
                key: "minZoomDistance",
                label: "Minimum zoom distance",
                type: "number",
                defaultValue: 5,
                owner: "camera",
                min: 0.1,
                step: 0.1,
            },
            {
                key: "maxZoomDistance",
                label: "Maximum zoom distance",
                type: "number",
                defaultValue: 12000,
                owner: "camera",
                min: 1,
                step: 10,
            },
        ],
    },
    debug: {
        label: "Debug",
        summary: "Labels, vectors, overlays, energy, and momentum diagnostics.",
        description: "Change according to what needs to be tracked",
        controls: [
            {
                key: "uiToggles",
                label: "UI toggles",
                type: "booleanGroup",
                defaultValue: {
                    showLabels: true,
                    showVelocityVectors: false,
                    showAccelerationVectors: false,
                    showBarycenterMarker: false,
                },
                owner: "renderer",
                options: [
                    { value: "showLabels", label: "Show labels" },
                    { value: "showVelocityVectors", label: "Velocity vectors" },
                    { value: "showAccelerationVectors", label: "Acceleration vectors" },
                    { value: "showBarycenterMarker", label: "Barycenter marker" },
                ],
            },
            {
                key: "performanceOverlay",
                label: "Performance overlay",
                type: "booleanGroup",
                defaultValue: {
                    fpsCounter: false,
                    frameTimeGraph: false,
                    simulationStepTime: false,
                },
                owner: "renderer",
                options: [
                    { value: "fpsCounter", label: "FPS counter" },
                    { value: "frameTimeGraph", label: "Frame time graph" },
                    { value: "simulationStepTime", label: "Simulation step time" },
                ],
            },
            {
                key: "showEnergyGraph",
                label: "Energy tracking",
                type: "boolean",
                defaultValue: false,
                owner: "python",
                description: "Displays E = K + U when backend energy data is available.",
            },
            {
                key: "momentumCheck",
                label: "Momentum check",
                type: "boolean",
                defaultValue: true,
                owner: "python",
                description: "Warns when summed system momentum differs from zero beyond backend tolerance.",
            },
        ],
    },
};
